# HTTP服务端口
httpPort: 3000

# 插件黑名单（不会执行）
pluginBlacklist:
  - example-plugin

# HTTP服务黑名单（不会自动启动）
httpServiceBlacklist:
  - example

# 通知配置
notification:
  email:
    use: false
    host: smtp.example.com
    port: 465
    secure: true
    user: your@email.com
    password: your-password
    to: recipient@email.com
  
  gotify:
    use: false
    url: https://gotify.example.com
    token: your-gotify-token
